// Headless harness for parlay.html — the markdown renderer and the age logic.
// Same idiom as selftest.js: extract the page's <script>, run it, poke at P.
// P.init() bails without a document, so `new Function` can hand P straight back.
const fs=require('fs'), path=require('path');
const src=fs.readFileSync(path.join(__dirname,'parlay.html'),'utf8');
const js=src.slice(src.indexOf('<script>')+8, src.lastIndexOf('</script>'));
const P=new Function(js+';return P;')();

let pass=0,fail=0;
const chk=(c,m)=>{(c?pass++:fail++);console.log((c?'PASS  ':'FAIL  ')+m);};

// --- the stamp: BOARD.md's H1 is the only timestamp this page trusts --------
const s=P.stamp('# Board report — 2026-08-05 17:03 UTC\n\nAuto-generated by the daily refresh.');
chk(!!s, 'the real H1 form parses at all');
chk(s&&s.label==='2026-08-05 17:03 UTC', `label is the stamp verbatim (${s&&s.label})`);
chk(s&&s.ms===Date.parse('2026-08-05T17:03:00Z'),
    'ms is built as ISO+Z by hand (Safari cannot parse the raw form, and the phone is where this page lives)');
chk(P.stamp('# Board report — the refresh died mid-write')===null,
    'no stamp -> null, not NaN smuggled through');

// --- the colours: same statement as the hub dot ------------------------------
chk(P.colour(3)==='#4ad6a2',  '3h -> green');
chk(P.colour(11.9)==='#4ad6a2','11.9h -> still green');
chk(P.colour(12)==='#e8b44a', '12h -> amber ("green under 12h" means UNDER)');
chk(P.colour(19)==='#e8b44a', '19h (the healthy overnight gap) -> amber, by design');
chk(P.colour(24)==='#e06c75', '24h -> red (both daily runs missed)');
chk(P.age(0.5)==='30m' && P.age(19)==='19h', `age reads human (${P.age(0.5)}, ${P.age(19)})`);

// --- the renderer: exactly the subset the two files are written in -----------
const table=P.render('| # | leg | price |\n|---|---|---|\n| 1 | NYM@CLE F5 Under 10.5 | -7000 |');
chk(/<thead><tr><th>#<\/th><th>leg<\/th><th>price<\/th>/.test(table),
    'a pipe table grows a real thead');
chk(/<td>NYM@CLE F5 Under 10.5<\/td>/.test(table), 'cells survive trimming intact');
chk(/tblwrap/.test(table), 'tables are wrapped for phone-width overflow-x scrolling');

const fenced=P.render('```\n #  leg        price\n 1  **not bold**  -7000\n```');
chk(/<pre>/.test(fenced) && /-7000/.test(fenced), 'solver output lands in a <pre> verbatim');
chk(/\*\*not bold\*\*/.test(fenced) && !/<strong>/.test(fenced),
    'inline markup is NOT applied inside fences');

const boxes=P.render('- [ ] Wed 8/5 7:00p — New York Liberty ML\n- [x] Legs 1–13 — ALL WON');
chk(/class="todo"/.test(boxes) && /New York Liberty/.test(boxes), 'an open leg renders unticked');
chk(/class="done"/.test(boxes) && /✓/.test(boxes), 'a settled leg renders ticked');

const md=P.render('# H1 — title\n\n## H2\n\n### H3\n\n**13/13 settled legs WON** and `code` here.\n\n---\n');
chk(/<h1>H1 — title<\/h1>/.test(md) && /<h2>H2<\/h2>/.test(md) && /<h3>H3<\/h3>/.test(md),
    'three heading levels');
chk(/<strong>13\/13 settled legs WON<\/strong>/.test(md), 'bold');
chk(/<code>code<\/code>/.test(md), 'inline code');
chk(/<hr>/.test(md), 'a --- rule renders (and is not confused with a table separator)');

chk(!/<img/.test(P.render('hello <img src=x onerror=alert(1)> there')),
    'HTML in the source is escaped, never interpreted');

// unclosed fence: a refresh that died mid-write must still render, not vanish
chk(/<pre>/.test(P.render('```\nhalf a block')), 'an unclosed fence still renders as a block');

console.log(`\n${pass}/${pass+fail} checks pass`);
process.exit(fail?1:0);
