// Headless harness for TheTool's freshness + routing logic.
const fs=require('fs'), path=require('path');
// __dirname, not a hardcoded absolute path: the repo checks out at a different
// root in every container, and a selftest that can't find its subject "passes"
// by crashing.
const src=fs.readFileSync(path.join(__dirname,'index.html'),'utf8');
const js=src.slice(src.indexOf('<script>')+8, src.lastIndexOf('</script>'));

let pass=0,fail=0;
const chk=(c,m)=>{(c?pass++:fail++);console.log((c?'PASS  ':'FAIL  ')+m);};

// --- DOM + fetch stubs -------------------------------------------------
const dots={};
function mkEl(){return {className:'',dataset:{},style:{},title:'',innerHTML:'',
  classList:{toggle(){},add(){},remove(){}},appendChild(){},
  removeAttribute(){},addEventListener(){},setAttribute(){}};}
const nodes={frame:mkEl(),load:mkEl(),loadTxt:mkEl(),err:mkEl(),nav:mkEl(),topbar:mkEl()};
let FETCHES=[];
let RESP={};   // url -> {ok, status, json, text, throw}
global.document={
  getElementById:id=>nodes[id]||mkEl(),
  createElement:()=>mkEl(),
  querySelectorAll:sel=>{
    const m=/\[data-dot="(\w+)"\]/.exec(sel);
    if(m){ dots[m[1]]=dots[m[1]]||mkEl(); return [dots[m[1]]]; }
    return [];
  },
  get title(){return '';}, set title(v){},
};
global.location={hash:''};
global.window={addEventListener(){}};
global.fetch=(u,o)=>{
  FETCHES.push([u,(o&&o.method)||'GET']);
  const r=RESP[u];
  if(r===undefined) return Promise.reject(new Error('no route'));
  if(r.throw) return Promise.reject(new Error(r.throw));
  return Promise.resolve({ok:r.ok!==false,status:r.status||200,
    json:()=>Promise.resolve(r.json), text:()=>Promise.resolve(r.text)});
};

const NOW=Date.parse('2026-08-03T20:00:00Z');
const RealDate=Date;
global.Date=class extends RealDate{
  constructor(...a){ super(...(a.length?a:[NOW])); }
  static now(){return NOW;}
  static parse(s){return RealDate.parse(s);}
};

const PAR='https://raw.githubusercontent.com/CheeseDagg/parlay/main/BOARD.md';

RESP['/MLBTool/mlb/data/slate.json']={json:{generated:'2026-08-03T19:14:12+00:00'}}; // 0.8h
RESP['/NFLTool/data/slate.json']     ={json:{generated:'2026-08-01T20:00:00+00:00'}}; // 48h
RESP['/SoccerTool/data/slate.json']  ={json:{generated:'2026-07-28T20:00:00+00:00'}}; // 144h
// UFC has no slate.json -- its board is inlined into a 2.9MB page at build time -- but
// refresh_odds.py stamps docs/status.json before every rebuild, and that is a real
// build timestamp in a different field. This dot was switched off on the assumption
// that no timestamp existed.
RESP['/UFC-ODDS/status.json']        ={json:{odds_asof:'2026-08-03T14:00+00:00'}};     // 6h
// Parlay's stamp is not JSON at all: it is the H1 of BOARD.md, committed by the
// refresh workflow. The dot reads the markdown itself.
RESP[PAR]={text:'# Board report — 2026-08-03 17:03 UTC\n\nAuto-generated by the daily refresh.\n'}; // 3h
new Function(js)();

setTimeout(()=>{
  chk(dots.soc!==undefined, 'Soccer now has a freshness dot at all (it had none)');
  chk(dots.ufc!==undefined, 'UFC now has a freshness dot at all (it had none)');
  chk(dots.ufc&&dots.ufc.style.background==='#4ad6a2',
      `UFC reads its own field (odds_asof, not generated) -> green (${dots.ufc&&dots.ufc.style.background})`);
  chk(dots.ufc&&/updated 6h ago/.test(dots.ufc.title),
      `UFC tooltip carries the age (${dots.ufc&&dots.ufc.title})`);
  chk(dots.mlb.style.background==='#4ad6a2', `fresh -> green (${dots.mlb.style.background})`);
  chk(dots.nfl.style.background==='#e8b44a', `48h -> amber (${dots.nfl.style.background})`);
  chk(dots.soc.style.background==='#e06c75', `144h -> red (${dots.soc.style.background})`);
  chk(/updated 48h ago/.test(dots.nfl.title), `tooltip carries the age (${dots.nfl.title})`);
  chk(!/checking/.test(dots.soc.title), 'no dot is left saying "checking freshness…"');
  chk(dots.par!==undefined, 'Parlay has a freshness dot');
  chk(dots.par&&dots.par.style.background==='#4ad6a2',
      `a 3h-old BOARD.md stamp -> green (${dots.par&&dots.par.style.background})`);
  chk(dots.par&&/2026-08-03 17:03 UTC/.test(dots.par.title),
      `the tooltip carries the parsed stamp (${dots.par&&dots.par.title})`);

  // round 2: failures must be VISIBLY unknown, not silently grey and not red
  Object.keys(dots).forEach(k=>delete dots[k]);
  RESP['/MLBTool/mlb/data/slate.json']={throw:'network down'};
  RESP['/NFLTool/data/slate.json']={ok:false,status:404};
  RESP['/SoccerTool/data/slate.json']={json:{}};            // no `generated`
  RESP['/UFC-ODDS/status.json']={json:{event:'some card'}};  // status.json, no odds_asof
  RESP[PAR]={text:'# Board report — the refresh died before stamping\n'};   // no stamp
  new Function(js)();
  setTimeout(()=>{
    chk(dots.mlb.style.background==='#6b5bd0'&&/could not read/.test(dots.mlb.title),
        `a failed fetch reads UNKNOWN, not stale (${dots.mlb.style.background} / ${dots.mlb.title})`);
    chk(dots.nfl.style.background==='#6b5bd0'&&/HTTP 404/.test(dots.nfl.title),
        `a 404 reads UNKNOWN and names the status (${dots.nfl.title})`);
    chk(dots.soc.style.background==='#6b5bd0'&&/no readable/.test(dots.soc.title),
        `a missing timestamp reads UNKNOWN, not red (${dots.soc.title})`);
    chk(dots.mlb.style.background!=='#e06c75',
        'and specifically NOT red -- "I could not tell" is not "it is old"');
    chk(dots.ufc.style.background==='#6b5bd0'&&/odds_asof/.test(dots.ufc.title),
        `a status.json with no odds_asof reads UNKNOWN and names the field (${dots.ufc.title})`);
    chk(dots.par.style.background==='#6b5bd0'&&/no readable/.test(dots.par.title),
        `a BOARD.md with no stamp reads UNKNOWN, not red (${dots.par.title})`);
    chk(FETCHES.some(([u,m])=>m==='HEAD'), 'the selected tool URL is HEAD-checked for a 404');
    chk(FETCHES.some(([u])=>/\?r=\d+/.test(u)) || nodes.frame.src&&/\?r=\d+/.test(nodes.frame.src),
        'the frame src is cache-busted');

    // round 3: 19h is what a HEALTHY board looks like every morning (the
    // 21:00 -> 16:00 overnight gap). Per-tool ok:12 must beat the global
    // FRESH_OK=30, which would have painted this green and hidden the schedule.
    Object.keys(dots).forEach(k=>delete dots[k]);
    RESP[PAR]={text:'# Board report — 2026-08-03 01:00 UTC\n'};   // 19h
    new Function(js)();
    setTimeout(()=>{
      chk(dots.par.style.background==='#e8b44a',
          `19h (the overnight gap) -> amber via per-tool ok:12, not green via global 30 (${dots.par.style.background})`);
      chk(/updated 19h ago/.test(dots.par.title), `tooltip carries the age (${dots.par.title})`);

      // round 4: 25h means BOTH of today's runs missed. Per-tool warn:24 must
      // beat the global FRESH_WARN=60, which would still have said amber.
      Object.keys(dots).forEach(k=>delete dots[k]);
      RESP[PAR]={text:'# Board report — 2026-08-02 19:00 UTC\n'};  // 25h
      new Function(js)();
      setTimeout(()=>{
        chk(dots.par.style.background==='#e06c75',
            `25h (both daily runs missed) -> red via per-tool warn:24 (${dots.par.style.background})`);
        console.log(`\n${pass}/${pass+fail} checks pass`);
        process.exit(fail?1:0);
      },20);
    },20);
  },20);
},20);
