// Headless harness for parlay.html — the markdown renderer and the age logic.
// Same idiom as selftest.js: extract the page's <script>, run it, poke at P.
// P.init() bails without a document, so `new Function` can hand P straight back.
const fs=require('fs'), path=require('path');
const src=fs.readFileSync(path.join(__dirname,'parlay.html'),'utf8');
const js=src.slice(src.indexOf('<script>')+8, src.lastIndexOf('</script>'));
const P=new Function(js+';return P;')();

let pass=0,fail=0;
const chk=(c,m)=>{(c?pass++:fail++);console.log((c?'PASS  ':'FAIL  ')+m);};

// --- the stamp: BOARD.md's H1 is the only timestamp this page trusts --------
const s=P.stamp('# Board report — 2026-08-05 17:03 UTC\n\nAuto-generated by the daily refresh.');
chk(!!s, 'the real H1 form parses at all');
chk(s&&s.label==='2026-08-05 17:03 UTC', `label is the stamp verbatim (${s&&s.label})`);
chk(s&&s.ms===Date.parse('2026-08-05T17:03:00Z'),
    'ms is built as ISO+Z by hand (Safari cannot parse the raw form, and the phone is where this page lives)');
chk(P.stamp('# Board report — the refresh died mid-write')===null,
    'no stamp -> null, not NaN smuggled through');

// --- the colours: same statement as the hub dot ------------------------------
chk(P.colour(3)==='#4ad6a2',  '3h -> green');
chk(P.colour(11.9)==='#4ad6a2','11.9h -> still green');
chk(P.colour(12)==='#e8b44a', '12h -> amber ("green under 12h" means UNDER)');
chk(P.colour(19)==='#e8b44a', '19h (the healthy overnight gap) -> amber, by design');
chk(P.colour(24)==='#e06c75', '24h -> red (both daily runs missed)');
chk(P.age(0.5)==='30m' && P.age(19)==='19h', `age reads human (${P.age(0.5)}, ${P.age(19)})`);

// --- the renderer: exactly the subset the two files are written in -----------
const table=P.render('| # | leg | price |\n|---|---|---|\n| 1 | NYM@CLE F5 Under 10.5 | -7000 |');
chk(/<thead><tr><th>#<\/th><th>leg<\/th><th>price<\/th>/.test(table),
    'a pipe table grows a real thead');
chk(/<td>NYM@CLE F5 Under 10.5<\/td>/.test(table), 'cells survive trimming intact');
chk(/tblwrap/.test(table), 'tables are wrapped for phone-width overflow-x scrolling');

const fenced=P.render('```\n #  leg        price\n 1  **not bold**  -7000\n```');
chk(/<pre>/.test(fenced) && /-7000/.test(fenced), 'solver output lands in a <pre> verbatim');
chk(/\*\*not bold\*\*/.test(fenced) && !/<strong>/.test(fenced),
    'inline markup is NOT applied inside fences');

const boxes=P.render('- [ ] Wed 8/5 7:00p — New York Liberty ML\n- [x] Legs 1–13 — ALL WON');
chk(/class="todo"/.test(boxes) && /New York Liberty/.test(boxes), 'an open leg renders unticked');
chk(/class="done"/.test(boxes) && /✓/.test(boxes), 'a settled leg renders ticked');

const md=P.render('# H1 — title\n\n## H2\n\n### H3\n\n**13/13 settled legs WON** and `code` here.\n\n---\n');
chk(/<h1>H1 — title<\/h1>/.test(md) && /<h2>H2<\/h2>/.test(md) && /<h3>H3<\/h3>/.test(md),
    'three heading levels');
chk(/<strong>13\/13 settled legs WON<\/strong>/.test(md), 'bold');
chk(/<code>code<\/code>/.test(md), 'inline code');
chk(/<hr>/.test(md), 'a --- rule renders (and is not confused with a table separator)');

chk(!/<img/.test(P.render('hello <img src=x onerror=alert(1)> there')),
    'HTML in the source is escaped, never interpreted');

// unclosed fence: a refresh that died mid-write must still render, not vanish
chk(/<pre>/.test(P.render('```\nhalf a block')), 'an unclosed fence still renders as a block');

// --- the live grader: pure parts -------------------------------------------
const TICK = [
  '# Live slips', '',
  '## Slip A — 20-leg · whatever', '',
  '- [ ] Wed 8/5 7:00p — New York Liberty ML (WNBA) — -355 *(shared with Slip B)*',
  '- [ ] Sat 8/8 — Callum Walsh (boxing) — not on the board pulls · ≈0.81',
  '- [x] Legs 1–13 — ALL WON, settled through Tue 8/4', '',
  '## Slip B — 17-leg · placed @ +4140', '',
  '- [ ] Wed 8/5 7:11p — CWS@BOS F5 Under 6.5 — -340 *(printed a tick under the -350 floor)*',
  '- [ ] Fri 8/7 9:00p — Saskatchewan Roughriders ML — -430',
  '## Dead this week', '',
  '- HR trio, 100% boost — lost Tue 8/4.',
].join('\n');
const slips=P.parseSlips(TICK);
chk(slips.length===2, `two "## Slip" sections parse, Dead-this-week does not (${slips.length})`);
chk(slips[0].legs.length===3 && slips[1].legs.length===2, 'checkbox legs land under the right slip');
chk(slips[0].legs[0].lab==='New York Liberty ML (WNBA)' && slips[0].legs[0].day==='8/5',
    'the em-dash split survives trailing notes');
chk(slips[0].legs[2].done===true, 'a ticked box parses as done');

chk(P.legKind('CWS@BOS F5 Under 6.5').f5===true && P.legKind('CWS@BOS F5 Under 6.5').line===6.5,
    'F5 alternate totals classify with their line');
chk(P.legKind('ATH@CIN Under 13.5').f5===false, 'full-game totals are not F5');
chk(P.legKind('New York Liberty ML (WNBA)').sport==='basketball/wnba', 'Liberty routes to ESPN WNBA');
chk(P.legKind('Saskatchewan Roughriders ML').sport==='football/cfl', 'Roughriders route to ESPN CFL');
chk(P.legKind('Callum Walsh (boxing)').kind==='other', 'boxing has no live wire and says so');

chk(P.abEq('ARI','AZ') && P.abEq('AZ','ARI') && P.abEq('ATH','OAK') && !P.abEq('ARI','ATL'),
    'board/statsapi abbreviation aliases match both directions and nothing else');

const INN=[{away:{runs:1},home:{runs:0}},{away:{runs:0},home:{runs:2}},{away:{runs:0},home:{runs:0}},
           {away:{runs:1},home:{}},{away:{runs:0},home:{runs:1}},{away:{runs:9},home:{runs:9}}];
chk(P.f5sum(INN)===5, `f5sum takes exactly the first five innings and tolerates a missing half (${P.f5sum(INN)})`);
chk(P.f5done({currentInning:5,inningState:'Middle'},false)===false,
    'middle of the 5th is NOT done — the home half can still lose an under');
chk(P.f5done({currentInning:5,inningState:'End'},false)===true, 'end of the 5th settles F5');
chk(P.f5done({currentInning:3},true)===true, 'a Final settles F5 regardless of innings');

chk(P.gradeTotal(7,6.5,'Under',false)==='lost', 'an under passed mid-game is lost, no waiting');
chk(P.gradeTotal(5,6.5,'Under',false)==='live', 'an under still below the line mid-game is live');
chk(P.gradeTotal(5,6.5,'Under',true)==='won',  'an under below the line at the horn is won');
chk(P.gradeTotal(7,6.5,'Over',false)==='won',  'an over passed mid-game is already won');
chk(P.gradeTotal(5,6.5,'Over',true)==='lost',  'an over short at the horn is lost');

console.log(`\n${pass}/${pass+fail} checks pass`);
process.exit(fail?1:0);
